package hibernateclass;

/**
 * StudenciUczelnia generated by hbm2java
 */

public class StudenciUczelnia  implements java.io.Serializable {


     //Pola klasy stundeci
     private String studentId;
     private String nazwisko;
     private String imie;
     private String pesel;
     private String dataUr;
     private String miasto;
     private String kod;
     private String ulica;
     private String numer;
     private String tel;
     private String EMail;
     private String uczelnia;

  //{   Konstruktory  
    public StudenciUczelnia() {
    }

	
    public StudenciUczelnia(String studentId) {
        this.studentId = studentId;
    }
    
   
       public StudenciUczelnia(String studentId, String nazwisko, String imie, String pesel, String dataUr, String miasto, String kod, String ulica, String numer, String tel, String EMail, String uczelnia) {
       this.studentId = studentId;
       this.nazwisko = nazwisko;
       this.imie = imie;
       this.pesel = pesel;
       this.dataUr = dataUr;
       this.miasto = miasto;
       this.kod = kod;
       this.ulica = ulica;
       this.numer = numer;
       this.tel = tel;
       this.EMail = EMail;
       this.uczelnia = uczelnia;
    }
   //}
    
   //getery i settery
       
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getPesel() {
        return this.pesel;
    }
    
    public void setPesel(String pesel) {
        this.pesel = pesel;
    }
    public String getDataUr() {
        return this.dataUr;
    }
    
    public void setDataUr(String dataUr) {
        this.dataUr = dataUr;
    }
    public String getMiasto() {
        return this.miasto;
    }
    
    public void setMiasto(String miasto) {
        this.miasto = miasto;
    }
    public String getKod() {
        return this.kod;
    }
    
    public void setKod(String kod) {
        this.kod = kod;
    }
    public String getUlica() {
        return this.ulica;
    }
    
    public void setUlica(String ulica) {
        this.ulica = ulica;
    }
    public String getNumer() {
        return this.numer;
    }
    
    public void setNumer(String numer) {
        this.numer = numer;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public String getUczelnia() {
        return this.uczelnia;
    }
    
    public void setUczelnia(String uczelnia) {
        this.uczelnia = uczelnia;
    }

    




}


